<?php

return [
    [   
        'id' => '21',
        'address' => 'Via Alzaia Naviglio Grande, 62',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '22',
        'address' => 'Via San Vito, 26',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '23',
        'address' => 'Via Alserio, 19',
        'city' => 'Milano',
        'zip_code' => '20159',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '24',
        'address' => 'Via Edmondo de Amicis, 39',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '25',
        'address' => 'Corso di Porta Ticinese, 89',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '26',
        'address' => 'Via Col Di Lana, 8',
        'city' => 'Milano',
        'zip_code' => '20136',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '27',
        'address' => 'Via Brioschi, 16',
        'city' => 'Milano',
        'zip_code' => '20136',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '28',
        'address' => 'Via Vetere, 7',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '29',
        'address' => 'Via Ruggero di Lauria, 17',
        'city' => 'Milano',
        'zip_code' => '20149',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '30',
        'address' => 'Via Felice Casati, 39',
        'city' => 'Milano',
        'zip_code' => '20124',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '31',
        'address' => 'Via Galvani, 27',
        'city' => 'Milano',
        'zip_code' => '20122',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '32',
        'address' => 'Via Felice Casati, 39',
        'city' => 'Milano',
        'zip_code' => '20124',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '33',
        'address' => 'Via Amedei, 5',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '34',
        'address' => 'Via Coldilana, 1',
        'city' => 'Milano',
        'zip_code' => '20136',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '35',
        'address' => 'Via Albricci, 8',
        'city' => 'Milano',
        'zip_code' => '20122',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '36',
        'address' => 'Via Savona, 17',
        'city' => 'Milano',
        'zip_code' => '20144',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '37',
        'address' => 'Via Carlo Ravizza, 11',
        'city' => 'Milano',
        'zip_code' => '20149',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '38',
        'address' => 'Piazza Erculea, 2',
        'city' => 'Milano',
        'zip_code' => '20122',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '39',
        'address' => 'Via Felice Casati, 39',
        'city' => 'Milano',
        'zip_code' => '20124',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '40',
        'address' => 'Via Alzaia Naviglio Grande, 44',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '41',
        'address' => 'Via Felice Casati, 38',
        'city' => 'Milano',
        'zip_code' => '20124',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '42',
        'address' => 'Viale Monza, 90',
        'city' => 'Milano',
        'zip_code' => '20127',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '43',
        'address' => 'Passaggio Duomo, 2',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '44',
        'address' => 'Passaggio Duomo, 20',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '45',
        'address' => 'Via Orefici, 10',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
];
