<?php

return [
    [   
        'id' => '1',
        'address' => 'Via Alzaia Naviglio Grande, 62',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '2',
        'address' => 'Via San Vito, 26',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '3',
        'address' => 'Via Alserio, 19',
        'city' => 'Milano',
        'zip_code' => '20159',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '4',
        'address' => 'Via Edmondo de Amicis, 39',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '5',
        'address' => 'Corso di Porta Ticinese, 89',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '6',
        'address' => 'Via Col Di Lana, 8',
        'city' => 'Milano',
        'zip_code' => '20136',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '7',
        'address' => 'Via Brioschi, 16',
        'city' => 'Milano',
        'zip_code' => '20136',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '8',
        'address' => 'Via Vetere, 7',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '9',
        'address' => 'Via Ruggero di Lauria, 17',
        'city' => 'Milano',
        'zip_code' => '20149',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '10',
        'address' => 'Via Felice Casati, 39',
        'city' => 'Milano',
        'zip_code' => '20124',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '11',
        'address' => 'Via Galvani, 27',
        'city' => 'Milano',
        'zip_code' => '20122',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '12',
        'address' => 'Via Felice Casati, 39',
        'city' => 'Milano',
        'zip_code' => '20124',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '13',
        'address' => 'Via Amedei, 5',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '14',
        'address' => 'Via Coldilana, 1',
        'city' => 'Milano',
        'zip_code' => '20136',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '15',
        'address' => 'Via Albricci, 8',
        'city' => 'Milano',
        'zip_code' => '20122',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '16',
        'address' => 'Via Savona, 17',
        'city' => 'Milano',
        'zip_code' => '20144',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '17',
        'address' => 'Via Carlo Ravizza, 11',
        'city' => 'Milano',
        'zip_code' => '20149',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '18',
        'address' => 'Piazza Erculea, 2',
        'city' => 'Milano',
        'zip_code' => '20122',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '19',
        'address' => 'Via Felice Casati, 39',
        'city' => 'Milano',
        'zip_code' => '20124',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '20',
        'address' => 'Via Alzaia Naviglio Grande, 44',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '21',
        'address' => 'Via Felice Casati, 38',
        'city' => 'Milano',
        'zip_code' => '20124',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '22',
        'address' => 'Viale Monza, 90',
        'city' => 'Milano',
        'zip_code' => '20127',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '23',
        'address' => 'Passaggio Duomo, 2',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '24',
        'address' => 'Passaggio Duomo, 20',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
    [
        'id' => '25',
        'address' => 'Via Orefici, 10',
        'city' => 'Milano',
        'zip_code' => '20123',
        'province' => 'mi',
        'country' => '',
    ],
];
