<?php

    return [
        'Antipasto',
        'Primo',
        'Secondo',
        'Dessert',
        'Crudo',
        'Pollo',
        'Manzo',
        'Anatra',
        'Vitello',
        'Pesce',
        'Pizza',
        'Hamburger',
        'Snack',
        'Bevande',
        'Alcolici',
        'Senza glutine',
        'Insalate',
        'Burrito',
        'Tacos',
        'Fajitas',
        'Uramaki',
        'Nigiri',
        'Hosomaki',
        'Temaki',
        'Zuppe',
    ];