<?php
    return [
            'Alcool',
            'Alla griglia',
            'Americano',
            'Asiatico',
            'Bagel',
            'Bakery',
            'Barbecue',
            'Bevande',
            'Bistecche',
            'Brunch',
            'Bubble tea',
            'Burger King',
            'Burrito',
            'Caffè',
            'Cinese',
            'Colazione',
            'Comfort food',
            'Consegna gratuita',
            'Coreano',
            'Crêpes',
            'Curry',
            'Dessert',
            'Falafel',
            'Fast food',
            'Fish and chips',
            'Frutti di mare',
            'Gelato',
            'Giapponese',
            'Greco',
            'Hamburger',
            'Hawaiano',
            'Healthy',
            'Indiano',
            'Insalate',
            'Italiano',
            'KFC',
            'Kebab',
            'Libanese',
            'McDonald\'s',
            'Mediorientale',
            'Messicano',
            'Nepalese',
            'Noodles',
            'Pakistano',
            'Pasta',
            'Piadina',
            'Pizza',
            'Poke',
            'Pollo',
            'Ramen',
            'Ravioli cinesi',
            'Sandwich',
            'Smoothie',
            'Spuntini',
            'Street food',
            'Succhi',
            'Sushi',
            'Tacos',
            'Tedesco',
            'Teppanyaki',
            'Thailandese',
            'Turco',
            'Wrap'
    ];