<?php 

return [
    [
        'user_id' => '1',
        'address_id' => '1',
        'calendar_id' => null,
        'name' => 'Officina del riso',
        'email' => 'officinadelriso@gmail.com',
        'phone' => '38992730210',
        'slug' => 'officina-del-riso',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '2',
        'restaurant_type' => [35],
        'img_path' => '/images/restaurant_images/officina_del_riso.jpeg',
    ],
    [
        'user_id' => '2',
        'address_id' => '2',
        'calendar_id' => null,
        'name' => 'Green Day',
        'email' => 'greenday@gmail.com',
        'phone' => '0242101120',
        'slug' => 'green-day',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '3',
        'restaurant_type' => [35,32],
        'img_path' => '/images/restaurant_images/green_day.jpeg',
    ],
    [
        'user_id' => '3',
        'address_id' => '3',
        'calendar_id' => null,
        'name' => 'The Best Food and Drink',
        'email' => 'thebestfoodanddrink@libero.it',
        'phone' => '3476847483',
        'slug' => 'the-best-food-and-drink',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '2',
        'restaurant_type' => [55,26,24,25],
        'img_path' => '/images/restaurant_images/the_best.jpeg',
    ],
    [
        'user_id' => '4',
        'address_id' => '4',
        'calendar_id' => null,
        'name' => 'Pasticceria Viscontea',
        'email' => 'pasticceriaviscontea@outlook.com',
        'phone' => '0239430081',
        'slug' => 'pasticceria-viscontea',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '4',
        'restaurant_type' => [22,27,16],
        'img_path' => '/images/restaurant_images/pasticceria_viscontea.jpeg',
    ],
    [
        'user_id' => '5',
        'address_id' => '5',
        'calendar_id' => null,
        'name' => 'Frankie\'s',
        'email' => 'frankies@libero.com',
        'phone' => '0291943289',
        'slug' => 'frankies',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '2',
        'restaurant_type' => [1,54,16,14],
        'img_path' => '/images/restaurant_images/frankie_s.jpeg',
    ],
    [
        'user_id' => '6',
        'address_id' => '6',
        'calendar_id' => null,
        'name' => 'Delivery Valley',
        'email' => 'deliveryvalley@gmail.com',
        'phone' => '0245497543',
        'slug' => 'delivery-valley',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '4',
        'restaurant_type' => [25,24],
        'img_path' => '/images/restaurant_images/delivery_valley.jpeg',
    ],
    [
        'user_id' => '7',
        'address_id' => '7',
        'calendar_id' => null,
        'name' => 'Ciapa El Taco',
        'email' => 'ciapaeltaco@gmail.com',
        'phone' => '3515351226',
        'slug' => 'ciapa-el-taco',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '4',
        'restaurant_type' => [55,41,24],
        'img_path' => '/images/restaurant_images/ciapa_el_taco.jpeg',
    ],
    [
        'user_id' => '8',
        'address_id' => '8',
        'calendar_id' => null,
        'name' => 'Sushi 2MI',
        'email' => 'sushi2mi@libero.it',
        'phone' => '3515778776',
        'slug' => 'sushi-2-mi',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '1',
        'restaurant_type' => [26,28,58,48],
        'img_path' => '/images/restaurant_images/sushi_2mi.jpeg',
    ],
    [
        'user_id' => '9',
        'address_id' => '9',
        'calendar_id' => null,
        'name' => 'Ribot',
        'email' => 'ribot@libero.it',
        'phone' => '0233001646',
        'slug' => 'ribot',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '3',
        'restaurant_type' => [9,30,7],
        'img_path' => '/images/restaurant_images/ribot.jpeg',
    ],
    [
        'user_id' => '10',
        'address_id' => '10',
        'calendar_id' => null,
        'name' => 'Insalatona',
        'email' => 'insalatona@gmail.com',
        'phone' => '0284105336',
        'slug' => 'insalatona',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '1',
        'restaurant_type' => [17,34,32],
        'img_path' => '/images/restaurant_images/insalatona.jpeg',
    ],
    [
        'user_id' => '11',
        'address_id' => '11',
        'calendar_id' => null,
        'name' => 'Ottolina Cafè',
        'email' => 'ottolinacafe@libero.it',
        'phone' => '0267380067',
        'slug' => 'ottolina-cafe',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '1',
        'restaurant_type' => [14,16,22,57],
        'img_path' => '/images/restaurant_images/ottolina_cafe.jpeg',
    ],
    [
        'user_id' => '12',
        'address_id' => '12',
        'calendar_id' => null,
        'name' => 'Santa Polenta',
        'email' => 'santapolenta@gmail.com',
        'phone' => '3498019128',
        'slug' => 'santa-polenta',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '2',
        'restaurant_type' => [1,35,45,8],
        'img_path' => '/images/restaurant_images/santa_polenta.jpeg',
    ],
    [
        'user_id' => '13',
        'address_id' => '13',
        'calendar_id' => null,
        'name' => 'Gastronomia Yamamoto',
        'email' => 'gastronomiayamamoto@gmail.com',
        'phone' => '0236741426',
        'slug' => 'gastronomia yamamoto',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '3',
        'restaurant_type' => [28,4],
        'img_path' => '/images/restaurant_images/gastronomia_yamamoto.jpeg',
    ],
    [
        'user_id' => '14',
        'address_id' => '14',
        'calendar_id' => null,
        'name' => 'Chihuahua Tacos',
        'email' => 'chihuahuatacos@gmail.com',
        'phone' => '0236742528',
        'slug' => 'chihuahua-tacos',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '2',
        'restaurant_type' => [41,46,24,58],
        'img_path' => '/images/restaurant_images/chihuahua_tacos.jpeg',
    ],
    [
        'user_id' => '15',
        'address_id' => '15',
        'calendar_id' => null,
        'name' => 'Nima Sushi',
        'email' => 'nimasushi@gmail.com',
        'phone' => '0247927764',
        'slug' => 'nima-sushi',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '3',
        'restaurant_type' => [57,28,48],
        'img_path' => '/images/restaurant_images/nima_sushi.jpeg',
    ],
    [
        'user_id' => '16',
        'address_id' => '16',
        'calendar_id' => null,
        'name' => 'Tannico Wine Bar',
        'email' => 'tannicowinebar@libero.it',
        'phone' => '0209946657',
        'slug' => 'tannico-wine-bar',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '5',
        'restaurant_type' => [1,8],
        'img_path' => '/images/restaurant_images/tannico_wine_bar.jpeg',
    ],
    [
        'user_id' => '17',
        'address_id' => '17',
        'calendar_id' => null,
        'name' => 'Lievità Ravizza',
        'email' => 'livitaravizza@libero.it',
        'phone' => '0240701454',
        'slug' => 'lievita-ravizza',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '1',
        'restaurant_type' => [6,35,8,47],
        'img_path' => '/images/restaurant_images/lievita_ravizza.jpeg',
    ],
    [
        'user_id' => '18',
        'address_id' => '18',
        'calendar_id' => null,
        'name' => 'Focacceria Manuelina',
        'email' => 'focacceriamanuelina@libero.it',
        'phone' => '0235999080',
        'slug' => 'focacceria-manuelina',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '3',
        'restaurant_type' => [6,47,46,8],
        'img_path' => '/images/restaurant_images/focacceria_manuelina.jpeg',
    ],
    [
        'user_id' => '19',
        'address_id' => '19',
        'calendar_id' => null,
        'name' => 'La Pasta di Nonna Rosa',
        'email' => 'lapastadinonnarosa@gmail.com',
        'phone' => '0249676591',
        'slug' => 'la-pasta-di-nonna-rosa',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '5',
        'restaurant_type' => [45,35,1,34],
        'img_path' => '/images/restaurant_images/la_pasta_di_nonna_rosa.jpeg',
    ],
    [
        'user_id' => '20',
        'address_id' => '20',
        'calendar_id' => null,
        'name' => 'CioccolatItaliani',
        'email' => 'cioccolatitaliani@gmail.com',
        'phone' => '0289093820',
        'slug' => 'cioccolatitaliani',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '2',
        'restaurant_type' => [20,22,27,8],
        'img_path' => '/images/restaurant_images/cioccolatitaliani.jpeg',
    ],
    [
        'user_id' => '21',
        'address_id' => '21',
        'calendar_id' => null,
        'name' => 'Lasagneria Italiana',
        'email' => 'lasagneriaitaliana@hotmail.it',
        'phone' => '0249676591',
        'slug' => 'lasagneria-italiana',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '1',
        'restaurant_type' => [35,45],
        'img_path' => '/images/restaurant_images/lasagneria_italiana.jpeg',
    ],
    [
        'user_id' => '22',
        'address_id' => '22',
        'calendar_id' => null,
        'name' => 'Ristorante Indiano Aangan',
        'email' => 'ristoranteindianoaangan@hotmail.it',
        'phone' => '0228510258',
        'slug' => 'ristorante-indiano-aangan',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '3',
        'restaurant_type' => [33,47],
        'img_path' => '/images/restaurant_images/ristorante_indiano_aangan.jpeg',
    ],
    [
        'user_id' => '23',
        'address_id' => '23',
        'calendar_id' => null,
        'name' => 'McDonald\'s',
        'email' => 'mcdonalds@gmail.com',
        'phone' => '0286997265',
        'slug' => 'mcdonalds',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '2',
        'restaurant_type' => [24,30,39],
        'img_path' => '/images/restaurant_images/mcdonald_s.jpeg',
    ],
    [
        'user_id' => '24',
        'address_id' => '24',
        'calendar_id' => null,
        'name' => 'Burger King',
        'email' => 'burgerking@gmail.com',
        'phone' => '0286331927',
        'slug' => 'burger-king',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '2',
        'restaurant_type' => [24,30,12],
        'img_path' => '/images/restaurant_images/burger_king.jpeg',
    ],
    [
        'user_id' => '25',
        'address_id' => '25',
        'calendar_id' => null,
        'name' => 'KFC',
        'email' => 'kfc@gmail.com',
        'phone' => '0283623002',
        'slug' => 'kfc',
        'take_away' => '0',
        'free_delivery' => '0',
        'delivery_price' => '3',
        'restaurant_type' => [36,24,49,3],
        'img_path' => '/images/restaurant_images/kfc.jpeg',
    ],
];
